export const MAXNORMALTEMPIN = 70
export const MAXNORMALTEMPOUT = 100
export const MINNORMALHASHRATE = 100000
export const MINNORMALFANSPEED = 4000
export const FAILURETHRESHOLD = 0.05
export const TELEMETRYPOINTS = 1